### ISSUE TITLE
mapas de karnaught

### ISSUE THREAD

**Issue by mae18-25** [SistemasTecTlaxiaco/actividad-12-ejercicios-de-mapas-de-karnaught-equipo-maetzy-quetzaly-angel-jesus#1]
[mapas de karnaugh.pdf](https://github.com/user-attachments/files/18066007/mapas.de.karnaugh.pdf)

**Comment by Eddi3mendoz** [comment]
Portada:25/25
Procedimiento/Desarrollo:25/25
Figuras, Ilustraciones y Fotografías:25/25
Resultados y conclusiones:25/25
Total: 20/20
Califico Edwin Eduardo Mendoza Cruz

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
